apiVersion: v1
kind: ReplicationController
metadata:
  name: szeged-jupyterhub-rc
spec:
  replicas: 1
  selector:
    name: szeged-jupyterhub
    version: v1
  template:
    metadata:
      labels:
        name: szeged-jupyterhub
        version: v1
    spec:
      containers:
        - name: jhub
          image: saibot94/jupyterhub-szeged
          ports:
            - containerPort: 8000
    