apiVersion: v1
kind: Service
metadata:
  labels:
    name: szeged-jupyterhub-service
  name: szeged-jupyterhub-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    name: szeged-jupyterhub